name: Mast Moves Post

on:
  schedule:
    - cron: "30 4 * * *"   # IST 10:00 AM
    - cron: "30 10 * * *"  # IST 04:00 PM
    - cron: "30 16 * * *"  # IST 10:00 PM
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # =========================
      # 1. PULL CODE
      # =========================
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # =========================
      # 2. SETUP PYTHON
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      # =========================
      # 3. INSTALL DEPENDENCIES
      # =========================
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright playwright-stealth cryptography python-dotenv requests

      - name: Install Playwright Chromium
        run: |
          python -m playwright install chromium

      # =========================
      # 4. RUN BOT
      # =========================
      - name: Run bot
        env:
          DECRYPT_KEY: ${{ secrets.DECRYPT_KEY }}
        run: python mast_moves.py

      # =========================
      # 5. COMMIT & PUSH CHANGES
      # =========================
      - name: Commit & Push updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Sirf mast_moves folder ke deletions stage karein
          git add mast_moves/
          
          # Check karein agar koi video delete hui hai
          if ! git diff --cached --quiet; then
            git commit -m "Post successful: Video removed [auto]"
            
            # Latest changes pull karein (Conflict avoid karne ke liye)
            git pull --rebase origin main
            
            # Push changes
            git push origin main
          else
            echo "No changes detected (No video was deleted). Skipping push."
          fi